name: PR

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: read

    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Setup npmrc for ketch-com
        uses: conventional-actions/setup-npmrc@fe8070df4c9863ba5f2f92ca274f037f6f89a060 # v2
        with:
          always-auth: true
          scope: ketch-com
          token: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Run all targets
        run: npm run all
